### ISSUE TITLE
Ship list

### ISSUE THREAD

**Issue by mdo** [poole/lanyon#1]
#### Todos
- [x] Add themes from Hyde (CSS and readme)
- [x] Update readme with new screenshots
- [ ] ~~Prevent space on copyright if no author with some `if/else`?~~
- [ ] ~~Hide the toggle on mobile viewports?~~
- [x] Fix shitty wrapping on opening post blockquote source
- [ ] ~~Pull in any new updates from Hyde 1.2 (new pages, config, etc)~~
- [x] Clean up `_config.yml`: sort unchanging globals from site customizations
- [x] Add RSS link in the features list in opening post
- [x] Change pagination font to `PT Sans`
- [x] Figure out an auto year for copyright, or manually bump to 2014
- [x] Document how to change `font-size`s in the readme
#### Ideas
- [x] On mobile, keep the toggle and do some vertical expansion? Center the title, hide the tagline, and left or right align the toggle. Use absolute positioning to swap placement of masthead and sidebar?
